=== AayushDangol123/xml-catalouge-website/xml website/codes/catalog_18029643.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Vehicle">
		<xs:complexType>
		    <xs:sequence>
				<xs:element ref="Shop"/>
				<xs:element ref="Header"/>
				<xs:element ref="Cars"/>
				<xs:element ref="Footer"/>
		    </xs:sequence>
		</xs:complexType>
    </xs:element>
	
	<xs:element name="Shop">
		<xs:complexType>
		    <xs:sequence>
				<xs:element ref="rowgap"/>
		    </xs:sequence>
		</xs:complexType>
    </xs:element>
	 <xs:element name="rowgap" type="xs:string"/>
	 
	<xs:element name="Header">
		<xs:complexType>
		    <xs:sequence>
				<xs:element ref="Logo"/>
				<xs:element ref="Name"/>
		    </xs:sequence>
		</xs:complexType>
    </xs:element>
	 <xs:element name="Logo" type="xs:string"/>
    <xs:element name="Name" type="xs:string"/>
	
   <xs:element name="Cars">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="Car" maxOccurs="unbounded" minOccurs="0"/>
			 </xs:sequence>
		</xs:complexType>
    </xs:element>
	
	 <xs:element name="Car">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="civic"/>
				<xs:element ref="row1"/>
				<xs:element ref="row2"/>
				<xs:element ref="img15" minOccurs="0"/>
				<xs:element ref="img25" minOccurs="0"/>
				<xs:element ref="img35" minOccurs="0"/>
				<xs:element ref="Price" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
   </xs:element>
   <!--civic-->
   <xs:element name="civic">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="img1" minOccurs="0"/>
				<xs:element ref="img2" minOccurs="0"/>
				<xs:element ref="img3" minOccurs="0"/>
				<xs:element ref="img4" minOccurs="0"/>
				<xs:element ref="img5" minOccurs="0"/>
				<xs:element ref="img6" minOccurs="0"/>
				<xs:element ref="img7" minOccurs="0"/>
				<xs:element ref="carmodel"/>
				<xs:element ref="Description"/>
			</xs:sequence>
		</xs:complexType>
    </xs:element>
	<xs:element name="img1" type="xs:string"/>
	 <xs:element name="img2" type="xs:string"/>
	 <xs:element name="img3" type="xs:string"/>
     <xs:element name="img4" type="xs:string"/>
     <xs:element name="img5" type="xs:string"/> 
     <xs:element name="img6" type="xs:string"/>
     <xs:element name="img7" type="xs:string"/>
    <xs:element name="carmodel" type="xs:string"/>
    <xs:element name="Description">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:element ref="p"/>
			</xs:sequence>
		</xs:complexType>
     </xs:element>
	<xs:element name="heading" type="xs:string"/>
    <xs:element name="p" type="xs:string"/>
	<!--row1-->
	<xs:element name="row1">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="spec1"/>
				<xs:element ref="spec2"/>
				<xs:element ref="img12" minOccurs="0"/>
				<xs:element ref="img22" minOccurs="0"/>
				<xs:element ref="img32" minOccurs="0"/>
				<xs:element ref="img42" minOccurs="0"/>
				<xs:element ref="img52" minOccurs="0"/>
				<xs:element ref="img62" minOccurs="0"/>
				<xs:element ref="img72" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!---element in row1-->
	<xs:element name="spec1">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="specs"/>
				<xs:element ref="Brand"/>
				<xs:element ref="Type"/>
				<xs:element ref="seatCapacity"/>
				<xs:element ref="carColor"/>
				<xs:element ref="weight"/>
				<xs:element ref="dimensions"/>
				<xs:element ref="driveType"/>
				<xs:element ref="displacement"/>
				<xs:element ref="engineConfiguration"/>
				<xs:element ref="boost"/>
			 </xs:sequence>
		</xs:complexType>
    </xs:element>
	 <xs:element name="specs" type="xs:string"/>
	 <xs:element name="Brand">
		<xs:complexType>
		  <xs:simpleContent>
			<xs:extension base="xs:string">
			  <xs:attribute type="xs:int" name="modelnum" use="optional"/>
			</xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	 </xs:element>
	<xs:element name="Type" type="xs:string"/>
	<xs:element name="seatCapacity" type="xs:string"/>
	<xs:element name="carColor" type="xs:string"/>
	<xs:element name="weight" type="xs:string"/>
	<xs:element name="dimensions">
		<xs:complexType>
		    <xs:simpleContent>
				<xs:extension base="xs:string">
				  <xs:attribute type="xs:string" name="unit" use="optional"/>
				</xs:extension>
		    </xs:simpleContent>
		</xs:complexType>
	  </xs:element>
	  <xs:element name="driveType" type="xs:string"/>
	  <xs:element name="displacement" type="xs:string"/>
	  <xs:element name="engineConfiguration" type="xs:string"/>
	  <xs:element name="boost">
		<xs:complexType>
		    <xs:simpleContent>
				<xs:extension base="xs:string">
				   <xs:attribute type="xs:string" name="pressureunit" use="optional"/>
				</xs:extension>
		     </xs:simpleContent>
		</xs:complexType>
	 </xs:element>
    <xs:element name="spec2">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="fuelCapacity"/>
				<xs:element ref="fuelEconomy"/>
				<xs:element ref="fuelType"/>
				<xs:element ref="transmission"/>
				<xs:element ref="suspension"/>
				<xs:element ref="brakeType"/>
				<xs:element ref="antiLockBraking"/>
				<xs:element ref="WheelSize"/>
				<xs:element ref="carPrice"/>
				<xs:element ref="quantity"/>
			 </xs:sequence>
		</xs:complexType>
    </xs:element>
	 <xs:element name="fuelCapacity" type="xs:string"/>
	<xs:element name="fuelEconomy">
		<xs:complexType>
		     <xs:simpleContent>
				<xs:extension base="xs:string">
				  <xs:attribute type="xs:string" name="value" use="optional"/>
				</xs:extension>
		    </xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fuelType" type="xs:string"/>
	<xs:element name="transmission" type="xs:string"/>
	<xs:element name="suspension" type="xs:string"/>
	<xs:element name="brakeType">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
				  <xs:attribute type="xs:string" name="breakalloy" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	  </xs:element>
	<xs:element name="antiLockBraking" type="xs:string"/>
	<xs:element name="WheelSize">
		<xs:complexType>
		    <xs:simpleContent>
				 <xs:extension base="xs:string">
				     <xs:attribute type="xs:string" name="measurement" use="optional"/>
				 </xs:extension>
		     </xs:simpleContent>
		</xs:complexType>
	  </xs:element>
	<xs:element name="carPrice">
		<xs:complexType>
		  <xs:simpleContent>
			<xs:extension base="xs:string">
			  <xs:attribute type="xs:string" name="currency" use="optional"/>
			</xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="quantity" type="xs:string"/>
	<xs:element name="img12" type="xs:string"/>
	<xs:element name="img22" type="xs:string"/>
    <xs:element name="img32" type="xs:string"/>
	<xs:element name="img42" type="xs:string"/>
	<xs:element name="img52" type="xs:string"/>
	<xs:element name="img62" type="xs:string"/>
	<xs:element name="img72" type="xs:string"/>
	<!-- row2-->
	<xs:element name="row2">
		 <xs:complexType>
			<xs:sequence>
				<xs:element ref="wrap13"/>
				<xs:element ref="wrap14"/>
			</xs:sequence>
		</xs:complexType>
    </xs:element>
	<!--elements in row2-->
	<!--elements in wrap13-->
	<xs:element name="wrap13">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="img13" minOccurs="0"/>
				<xs:element ref="img23" minOccurs="0"/>
				<xs:element ref="img33" minOccurs="0"/>
				<xs:element ref="img43" minOccurs="0"/>
				<xs:element ref="img53" minOccurs="0"/>
				<xs:element ref="img63" minOccurs="0"/>
				<xs:element ref="img73" minOccurs="0"/>
			 </xs:sequence>
		</xs:complexType>
    </xs:element>
	<xs:element name="img13" type="xs:string"/>
	 <xs:element name="img23" type="xs:string"/>
    <xs:element name="img33" type="xs:string"/>
	<xs:element name="img43" type="xs:string"/>
	<xs:element name="img53" type="xs:string"/>
	<xs:element name="img63" type="xs:string"/>
	<xs:element name="img73" type="xs:string"/>
		<!--elements in wrap14-->
    <xs:element name="wrap14">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="img14" minOccurs="0"/>
				<xs:element ref="img24" minOccurs="0"/>
				<xs:element ref="img34" minOccurs="0"/>
				<xs:element ref="img44" minOccurs="0"/>
				<xs:element ref="img54" minOccurs="0"/>
				<xs:element ref="img64" minOccurs="0"/>
				<xs:element ref="img74" minOccurs="0"/>
			 </xs:sequence>
		</xs:complexType>
    </xs:element>
	<!--elements in wrap14-->
	 <xs:element name="img14" type="xs:string"/>
	 <xs:element name="img24" type="xs:string"/>
	 <xs:element name="img34" type="xs:string"/>
	 <xs:element name="img44" type="xs:string"/>
	 <xs:element name="img54" type="xs:string"/>
	 <xs:element name="img64" type="xs:string"/>
	 <xs:element name="img74" type="xs:string"/>

	<xs:element name="img15" type="xs:string"/>
    <xs:element name="img25" type="xs:string"/>
	<xs:element name="img35" type="xs:string"/>
    <xs:element name="Price" type="xs:string"/>

  <!--footer-->
    <xs:element name="Footer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Logo"/>
				<xs:element ref="container"/>
				<xs:element ref="Follow"/>
			</xs:sequence>
		</xs:complexType>
    </xs:element>
	<xs:element name="container">
		<xs:complexType>
			 <xs:sequence>
				<xs:element ref="Location"/>
				<xs:element ref="Number"/>
				<xs:element ref="Website"/>
			 </xs:sequence>
		</xs:complexType>
	 </xs:element>
	<xs:element name="Location" type="xs:string"/>
    <xs:element name="Number" type="xs:string"/>
    <xs:element name="Website" type="xs:string"/>
    <xs:element name="Follow" type="xs:string"/>
</xs:schema>

=== AayushDangol123/xml-catalouge-website/xml website/codes/catalog_18029643.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Aayush Dangol -->
<!--03/24/2020-->
<?xml-stylesheet type="text/css" href="catalog_18029643.css"?>
<Vehicle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_18029643.xsd">
	<Shop>
	<rowgap/>
	</Shop>
	<Header>
	<Logo></Logo>
	<Name>Garage Motors</Name>
	</Header>
	<Cars>
		 <Car>
		<civic>
			<img1></img1>
			<carmodel></carmodel>
			<Description>
				<heading> Honda Civic </heading>
				<p>
					Honda's civic is a fourseated sports car which can also be used as a family car. 
					the car is front wheel drive.its engine pushes 205 ps of maximum power at 5700 rpm.
					it has 2.0 litre four-cylinder engine equipped with an optional turbo charger.
					it also comes with 1.5 litre v4 engine with two turbo chargers option variant.
					6 speed manual transmission or 8 speed automatic shifters are available for both the 
					engine variants.these vehichles gives 32 miles per gallon mileage.
			    </p>
			</Description>
			</civic>
			<row1>
			<spec1>
			<specs>Specifications</specs>
			<Brand modelnum="51581">Brand: Honda</Brand>
			<Type>Type: Sedan</Type>
			<seatCapacity>Seat Capacity: 4</seatCapacity>
			<carColor>Color: Black</carColor>
			<weight>curb weight: 2906 lbs</weight>
			<dimensions unit="feet">Dimension (L x W x H): 15.28 x 5.9 x 4.7) feet	</dimensions>
			<driveType>Drive Type: Front-Wheel-Drive</driveType>
			<displacement>Engine-displacement:1,498cc</displacement>
			<engineConfiguration>Engine-Type: In-Line 4-Cylinder with turbocharger</engineConfiguration>
			<boost pressureunit="pound per square inch">boost-pressure: 20.3 psi</boost>
			</spec1>
			<spec2>
			<fuelCapacity>Fuel Capacity: 12.39 gal</fuelCapacity>
			<fuelEconomy value="miles per gallon">City/Hwy: 48/47 mpg</fuelEconomy>
			<fuelType>Fuel Type: Petrol</fuelType>
			<transmission>Transmission: 6-speed manual trransmission</transmission>
			<suspension>Suspension: adaptive suspension system</suspension>
			<brakeType breakalloy="metal">Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking System: 4-Wheelabs with collission detection</antiLockBraking>			
			<WheelSize measurement="inch"> Wheel Size (inches):18inch in Matte Black Alloy</WheelSize>
			<carPrice currency="dollars">Starting Price: $25,200</carPrice>
			<quantity>In stock: 5</quantity>
			</spec2>
			<img12></img12>
			</row1> 
			<row2>
			<wrap13>
			<img13></img13>
			</wrap13>
			<wrap14>
			<img14></img14>
			</wrap14>
			</row2>
			<img15></img15>
		</Car>
		<Car>
		<civic>
		<img2></img2>
			<carmodel></carmodel>
			<Description>
				<heading> Corvette </heading>
				<p>
					The Chevrolet Corvette, colloquially known as the Vette,
					it is a two-door, two-passenger sports car manufactured and marketed by Chevrolet across more than 60 years of production and eight design generations.From 1953 to 2019, it was front-engined, and since 2020, it is mid-engined. With its generations noted sequentially from C1 to C8, the Corvette serves as Chevrolet's halo vehicle and is widely noted for its performance and distinctive plastic—either fiberglass or composite—bodywork.
				</p>
			</Description>
			</civic>
			<row1>
			<spec1>
			<specs>Specifications</specs>
			<Brand modelnum="5981">Brand: chevrolet</Brand>
			<Type>Type: coupe</Type>
			<seatCapacity>Seat Capacity: 2</seatCapacity>
			<carColor>Color: white</carColor>
			<weight>curb weight: 3,336 lbs</weight>
			<dimensions unit="feet">Dimension (L x W x H): 15.28 x 5.9 x 4.7) feet	</dimensions>
			<driveType>Drive Type: Front-Wheel-Drive</driveType>
			<displacement>Engine-displacement:6200cc</displacement>
			<engineConfiguration>Engine-Type: In-Line 8-Cylinder</engineConfiguration>
			<boost pressureunit="pound per square inch">boost-pressure: 29.3 psi</boost>
			</spec1>
			<spec2>
			<fuelCapacity>Fuel Capacity: 18.5 gal</fuelCapacity>
			<fuelEconomy value="miles per gallon">City/Hwy: 48/47 mpg</fuelEconomy>
			<fuelType>Fuel Type: diseal</fuelType>
			<transmission>Transmission: 8-speed dual-clutch trransmission</transmission>
			<suspension>Suspension: adaptive suspension system</suspension>
			<brakeType breakalloy="metal">Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking : 4-Wheel abs with collission detection and traction control</antiLockBraking>			
			<WheelSize measurement="inch"> Wheel Size (inches):18inch in Matte Black Alloy</WheelSize>
			<carPrice currency="dollars">Starting Price: $260,999</carPrice>
			<quantity>In stock: 2</quantity>
			</spec2>
			<img22></img22>
			</row1>
			<row2>
			<wrap13>
			<img23></img23>
			</wrap13>
			<wrap14>
			<img24></img24> 
			</wrap14>
			</row2>
			<img25></img25>	
		</Car>
		<Car>
		<civic>
		<img3></img3>
			<carmodel></carmodel>
			<Description>
				<heading> Koenigsegg Agera R </heading>
				<p>
					It can accelerate from 0–100 km/h (0–62 mph) in 2.8 seconds and attain a theoretical top speed of 439 km/h (273 mph). The Agera R has a drag coefficient of Cd=0.37, or Cd=0.33 at high speed due to its adaptive rear wing, while producing 300 kg (660 lb) of downforce at 250 km/h (155 mph).
				</p>
			</Description>
			</civic>
			
			<row1>
			<spec1>
			<specs>Specifications</specs>
			<Brand modelnum="2051">Brand: koenigsegg</Brand>
			<Type>Type: coupe</Type>
			<seatCapacity>Seat Capacity: 2</seatCapacity>
			<carColor>Color: Black</carColor>
			<weight>curb weight: 2086lbs</weight>
			<dimensions unit="feet">Dimension (L x W x H): 16.28 x 78.9 x 44.7) feet</dimensions>
			<driveType>Drive Type: Rear-Wheel-Drive</driveType>
			<displacement>Engine-displacement:5,000cc</displacement>
			<engineConfiguration>Engine-Type: V8,4 valves per cylinder</engineConfiguration>
			<boost pressureunit="pound per square inch">boost-pressure: 55.3 psi</boost>
			</spec1>
			<spec2>
			<fuelCapacity>Fuel Capacity: 12.39 gal</fuelCapacity>
			<fuelEconomy  value="miles per gallon">City/Hwy: 48/47 mpg</fuelEconomy>
			<fuelType>Fuel Type: Petrol</fuelType>
			<transmission>Transmission: 7-speed dual clutch trransmission</transmission>
			<suspension>Suspension: adaptive suspension system</suspension>
			<brakeType breakalloy="metal">Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking System: 4-Wheelabs with collission detection</antiLockBraking>			
			<WheelSize measurement="inch"> Wheel Size (inches):18inch in Matte Black Alloy</WheelSize>
			<carPrice currency="dollars">Starting Price: $25,200</carPrice>
			<quantity>In stock:8</quantity>
			</spec2>
			<img32></img32>
			</row1>
			<row2>
			<wrap13>
			<img33></img33>
			</wrap13>
			<wrap14>
			<img34></img34>
			</wrap14>
			</row2>
			<img35></img35>
			<Price></Price>
		</Car>
		<Car>
		<civic>
		<img4></img4>
			<carmodel></carmodel>
			<Description>
				<heading> Ford Mustang </heading>
				<p>
					Six available high-powered engines means that every 2020 Mustang comes with performance in its DNA. And with nine unique trims, you’ve got options, from the fun and energetic GT Convertible to the 2020 Shelby GT500® , host to the most power-dense supercharged V8 production engine in the world.
				</p>
			</Description>
			</civic>
			<row1>
			<spec1>
			<specs>Specifications</specs>
			<Brand modelnum="90181">Brand: Ford</Brand>
			<Type>Type: Sedan</Type>
			<seatCapacity>Seat Capacity: 2</seatCapacity>
			<carColor>Color: blue</carColor>
			<weight>curb weight: 2906 lbs</weight>
			<dimensions unit="feet">Dimension (L x W x H): 15.28 x 5.9 x 4.7) feet	</dimensions>
			<driveType>Drive Type: Front-Wheel-Drive</driveType>
			<displacement>Engine-displacement:1,498cc</displacement>
			<engineConfiguration>Engine-Type: In-Line 4-Cylinder with turbocharger</engineConfiguration>
			<boost pressureunit="pound per square inch">boost-pressure: 20.3 psi</boost>
			</spec1>
			<spec2>
			<fuelCapacity>Fuel Capacity: 12.39 gal</fuelCapacity>
			<fuelEconomy value="miles per gallon">City/Hwy: 48/47 mpg</fuelEconomy>
			<fuelType>Fuel Type: Petrol</fuelType>
			<transmission>Transmission: 6-speed manual trransmission</transmission>
			<suspension>Suspension: adaptive suspension system</suspension>
			<brakeType breakalloy="metal">Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking System: 4-Wheelabs with collission detection</antiLockBraking>			
			<WheelSize measurement="inch"> Wheel Size (inches):18inch in Matte Black Alloy</WheelSize>
			<carPrice currency="dollars">Starting Price: $25,200</carPrice>
			<quantity>In stock: 5</quantity>
			</spec2>
			<img42></img42>
			</row1>
			
			<row2>
			<wrap13>
			<img43></img43>
			</wrap13>
			<wrap14>
			<img44></img44>
			</wrap14>
			</row2>
		</Car>
		<Car>
		<civic>
		<img5></img5>
			<carmodel></carmodel>
			<Description>
				<heading> Lamborghini Avendator </heading>
				<p>
					The jewel in the crown is the car's V12 engine, hand-built in Sant'Agata Bolognese, naturally balanced and longitudinally mounted in a central position.  The excellent acceleration capabilities at any engine speed, the lightning-fast reactivity, and the breathtaking roar of the Aventador demonstrate the incredible power of its engine, the true beating heart of the car which is capable of taking you somewhere anything is possible: once you get there, you'll never want to go back. The feeling you get when you exceed all commonly accepted limits is simply indescribable. 
				</p>
			</Description>
			</civic>
			<row1>
			<spec1>
			<specs>Specifications</specs>
			<Brand modelnum="5951">Brand: lamborghini</Brand>
			<Type>Type: Sedan</Type>
			<seatCapacity>Seat Capacity: 2</seatCapacity>
			<carColor>Color: white</carColor>
			<weight>curb weight: 2906 lbs</weight>
